/* ROS */
#define NODE_NAME_PUB "ROS2LIB_ROS2_PUBLIHSH"
#define NODE_NAME_SUB "ROS2LIB_ROS2_SUBSCRIBE"
#define NODE_NAME_CLI "ROS2LIB_ROS2_CLIENT"
#define NODE_NAME_SRV "ROS2LIB_ROS2_SERVER"

#define NODE_NAME_T_PUB "ROS2LIB_T_ROS2_PUBLIHSH"
#define NODE_NAME_T_SUB "ROS2LIB_T_ROS2_SUBSCRIBE"
#define NODE_NAME_T_CLI "ROS2LIB_T_ROS2_CLIENT"
#define NODE_NAME_T_SRV "ROS2LIB_T_ROS2_SERVER"